### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by cechiorlu** [cechiorlu/heurics#4]
A logo for the app hasn't been created yet

A logo using #2c3e50 and #ffc0cb colors primarily should be created

**Comment by mandyellow** [comment]
Hello! I made a logo for your project. Let me know if you like it so I can open a PR with the PNG and an SVG (or another image format) to you. 🦊

Primary and negative logo:

![image](https://user-images.githubusercontent.com/30158643/94925568-cd8adc80-0495-11eb-93a0-954eda1fca07.png)

**Comment by cechiorlu** [comment]
Thank you Amanda! I love it!!

**Comment by mandyellow** [comment]
Awesome! Where I can upload the logos? Can I create 'images' maybe? 🦊 

And if you could tag your repository with "hacktoberfest" for my PR get valid, I would appreciate too (new hacktober's rules 😢 )

**Comment by cechiorlu** [comment]
It would be nice if you could upload the images to src/assets/images. Please include an image of just the puzzle for the favicon. I'll put your tag up right away. Thanks for contributing!
