### ISSUE TITLE
The web app seems to lack a responsive design.

### ISSUE THREAD

**Issue by KuzmanTheDev** [cechiorlu/heurics#5]
Redesign the app to be responsive at different viewports with css media queries

**Comment by cechiorlu** [comment]
![responsive layout](https://user-images.githubusercontent.com/71312063/95469331-71cdc100-0977-11eb-9fab-65dd30846a85.png)

This is what I came up with for the responsive layout. You can choose to style using this layout or completely disregard it. Creativity is encouraged!

**Comment by KuzmanTheDev** [comment]
Nice!! I'll work with this
